# Generated by Django 3.1.7 on 2021-03-23 12:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.unique_code, max_length=8, unique=True),
        ),
    ]
